/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JTable;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;

/**
 *
 * @author Ahmad Fariz
 */
public class Form_User extends javax.swing.JFrame {
    public Connection kon;
    public Statement stt;
    public ResultSet rs;

    /**
     * Creates new form Form_User
     */
    public Form_User() {
        initComponents();
        this.setSize(1071,641);
        this.setLocationRelativeTo(null);
        normal();
        tabel.setModel(tblModel);
        Tabel(tabel,new int[]{254,265,265,150});
        setDefaultTable();
    }
    
    private javax.swing.table.DefaultTableModel tblModel=getDefaulTableModel();
        private void Tabel(javax.swing.JTable tb, int lebar[]){
            tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            int kolom=tb.getColumnCount();
            for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc=tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }

    private javax.swing.table.DefaultTableModel getDefaulTableModel(){
            return new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Username","Password","TypeUser"}
            ){
                boolean[] canEdit=new boolean[]{
                false,false,false
                 };
                public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        tampil = new javax.swing.JCheckBox();
        typeuser = new javax.swing.JComboBox<>();
        tcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        ccari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Tipe User"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 370, 790, 200);
        getContentPane().add(username);
        username.setBounds(190, 180, 140, 40);
        getContentPane().add(password);
        password.setBounds(190, 230, 140, 40);

        tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilActionPerformed(evt);
            }
        });
        getContentPane().add(tampil);
        tampil.setBounds(335, 245, 20, 20);

        typeuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tipe User", "Admin", "Petugas" }));
        getContentPane().add(typeuser);
        typeuser.setBounds(190, 280, 140, 40);
        getContentPane().add(tcari);
        tcari.setBounds(830, 40, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1054, 600);

        tambah.setText("jButton1");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(640, 190, 100, 60);

        simpan.setText("jButton2");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(760, 193, 100, 60);

        hapus.setText("jButton3");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(880, 193, 100, 60);

        ubah.setText("jButton4");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah);
        ubah.setBounds(640, 263, 100, 60);

        batal.setText("jButton5");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal);
        batal.setBounds(760, 263, 100, 60);

        keluar.setText("jButton6");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(880, 263, 100, 60);

        ccari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccariActionPerformed(evt);
            }
        });
        getContentPane().add(ccari);
        ccari.setBounds(980, 30, 50, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
                String nm=username.getText();
                String ps=password.getText();
                    if((nm.isEmpty())|(ps.isEmpty())){
                    JOptionPane .showMessageDialog(null,"Masih Ada nilai yang kosong,silahkann dilengkapi");
                    username.requestFocus();
                    }
                else{
                    Object[]options = {"YA","TIDAK"};
                    int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menyimpan Data??","konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
                    if(konfirmasi==JOptionPane.YES_OPTION){
                    try{
                        koneksi();
                Statement stt=kon.createStatement();
                String sql="insert into login values('"+username.getText()+"','"+password.getText()+"','"+typeuser.getSelectedItem()+"')";
                stt.executeUpdate(sql);
                data[0]=username.getText();
                data[1]=password.getText();
                data[2]=typeuser.getSelectedItem().toString();
                tblModel.insertRow(0,data);
                normal();
                stt.close();
                kon.close();
                    }catch(Exception exc){
                    System.err.println(exc.getMessage());
                }
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        username.requestFocus();
        username.setEnabled(true);
        password.setEnabled(true);
        typeuser.setEnabled(true);
        tambah.setEnabled(false);
        simpan.setEnabled(true);
        ubah.setEnabled(false);
        batal.setEnabled(true);
        hapus.setEnabled(false);
        keluar.setEnabled(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Object[]options = {"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menghapus Data??","konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION){
                try{
                    koneksi();
            Statement stt=kon.createStatement();
            String SQL="delete from login where username ='"+username.getText()+"'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
            normal();
            stt.close();
            kon.close();
                }catch(Exception exc){
                System.err.println(exc.getMessage());
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
            if(evt.getClickCount()==1){
            Tampil();
            username.setEnabled(false);
            tambah.setEnabled(false);
            simpan.setEnabled(false);
            ubah.setEnabled(true);
            batal.setEnabled(true);
            hapus.setEnabled(true);
            keluar.setEnabled(false);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        Object[]options = {"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Mengupdate Data??","konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION){
                koneksi();
            try{
            Statement stt=kon.createStatement();
            String SQL="update login set password ='"+password.getText()+"',typeuser='"+typeuser.getSelectedItem()+"' where username='"+username.getText()+"'";
            stt.executeUpdate(SQL);
            data[0]=username.getText();
            data[1]=password.getText();
            data[2]=typeuser.getSelectedItem().toString();
            tblModel.removeRow(row);
            tblModel.insertRow(row, data);
            normal();
            stt.close();
            kon.close();
                    }catch(Exception exc){
                    System.err.println(exc.getMessage());
                }
            }
        normal();
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        normal();
        username.setEnabled(false);
        username.setText("");
        password.setEnabled(false);
        password.setText("");
        typeuser.setSelectedItem(false);
    }//GEN-LAST:event_batalActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        Object[]options = {"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Keluar?","konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void ccariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccariActionPerformed
        // TODO add your handling code here:
        koneksi();
        try{ String hubung = "jdbc:mysql://localhost:3306/poliklinik_fariz";
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection kon = DriverManager.getConnection(hubung,"root","");
        String cari=tcari.getText();
        String sql="select * from login where username like '"+cari+"'";
        Statement stt=kon.createStatement();
        ResultSet res=stt.executeQuery(sql);
        if(res.next()){
        username.setText(res.getString(1));
        password.setText(res.getString(2));
        typeuser.setSelectedItem(res.getString(3));
        username.setEnabled(true);
        password.setEnabled(true);
        typeuser.setEnabled(true);
        batal.setEnabled(true);
        hapus.setEnabled(true);
        ubah.setEnabled(true);
        tcari.setText("");
            }else{
            JOptionPane.showMessageDialog(null,"Data Tidak Ditemukan");
            }
            stt.close();
            kon.close();
            }catch (Exception e){
            System.out.println("Error."+e);
        }
    }//GEN-LAST:event_ccariActionPerformed

    private void tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilActionPerformed
        // TODO add your handling code here:
        if(tampil.isSelected() == false){
            password.setEchoChar('*');
            }else{
            password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_tampilActionPerformed

    private void koneksi(){
        try{
        String hubung="jdbc:mysql://localhost/poliklinik_fariz";
        Class.forName("com.mysql.jdbc.Driver");
        kon=DriverManager.getConnection(hubung,"root","");
        stt=kon.createStatement(rs.TYPE_SCROLL_SENSITIVE,rs.CONCUR_UPDATABLE);
        rs=stt.executeQuery("select*from login");
        }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.exit(0);
        }
    }
    
    public void normal(){
    username.setText("");
    password.setText("");
    username.setEnabled(false);
    password.setEnabled(false);
    typeuser.setEnabled(false);
    tambah.setEnabled(true);
    simpan.setEnabled(false);
    ubah.setEnabled(false);
    hapus.setEnabled(false);
    batal.setEnabled(false);
    keluar.setEnabled(true);
    }
    
    int row = 0;
    public void Tampil(){
    row= tabel.getSelectedRow();
    username.setText(tblModel.getValueAt(row,0).toString());
    password.setText(tblModel.getValueAt(row,1).toString());
    typeuser.setSelectedItem(tblModel.getValueAt(row,2).toString());
    username.setEnabled(true);
    password.setEnabled(true);
    typeuser.setEnabled(true);
    }
    
    String data[]=new String[3];
        public void setDefaultTable(){
        String hubung="jdbc:mysql://localhost:3306/poliklinik_fariz";
        try{
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection con= DriverManager.getConnection(hubung,"root","");
        Statement stt=con.createStatement();
        String sql ="Select*from login order by username asc";
        ResultSet res= stt.executeQuery(sql);
        while(res.next()){
        data[0]=res.getString(1);
        data[1]=res.getString(2);
        data[2]=res.getString(3);
        tblModel.addRow(data);
        }
            res.close();
            stt.close();
            con.close();
                } catch(Exception exc){
                System.err.println(exc.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton ccari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JCheckBox tampil;
    private javax.swing.JTextField tcari;
    private javax.swing.JComboBox<String> typeuser;
    private javax.swing.JButton ubah;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
