/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.mysql.jdbc.Statement;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Ahmad Fariz
 */
public class Menu extends javax.swing.JFrame {
Connection koneksi;
public static int kodeLogin=3;
ResultSet resultSet;
Statement statement;
    
    /**
     * Creates new form Menu
     * @param userName
     * @param userRole
     */
    public Menu(String userName, String userRole) {
        initComponents();
        this.setSize(1024,768);
        akun.setEnabled(true);
        data.setVisible(false);
        data.setEnabled(false);
        akun.setEnabled(true);
        keluar.setEnabled(true);
        
        setExtendedState(MAXIMIZED_BOTH);
        admin.setForeground(Color.red);
        kata.setText("Selamat datang di Poliklinik Mitra Medika");
        admin.setText(userName);
        kata.setEditable(false);
        
        if("Admin".equals(userRole)){
             kata.setText("Selamat datang. Anda login sebagai " + userRole + "");
             login.setEnabled(false);
             admin.setText(userName);
             akun.setEnabled(true);
             data.setVisible(true);
             data.setEnabled(true);
             akun.setEnabled(true);
             keluar.setEnabled(true);
        }if("Petugas".equals(userRole)){
             kata.setText("Selamat datang. Anda login sebagai " + userRole + "");
             admin.setText(userName);
             user.setEnabled(false);
             login.setEnabled(false);
             data.setVisible(true);
             data.setEnabled(true);
             akun.setEnabled(true);
             keluar.setEnabled(true);
       }
    }

    Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void belumLogin() {
     data.setEnabled(false);
     keluar.setEnabled(true);
     }
    
    private void loginAdmin() {
     data.setEnabled(true);
     akun.setVisible(false);
     }
    
     private void loginPublik() {
     data.setEnabled(false);
     akun.setVisible(false);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JLabel();
        kata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        akun = new javax.swing.JMenu();
        login = new javax.swing.JMenuItem();
        user = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        data = new javax.swing.JMenu();
        pegawai = new javax.swing.JMenuItem();
        pasien = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        getContentPane().add(admin);
        admin.setBounds(0, 0, 1366, 770);

        kata.setText("jTextField1");
        getContentPane().add(kata);
        kata.setBounds(90, 130, 63, 20);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 160, 41, 16);

        akun.setText("Akun");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        akun.add(login);

        user.setText("User Baru");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        akun.add(user);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        akun.add(logout);

        jMenuBar1.add(akun);

        data.setText("Data");

        pegawai.setText("Pegawai");
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });
        data.add(pegawai);

        pasien.setText("Pasien");
        data.add(pasien);

        jMenuBar1.add(data);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenuBar1.add(keluar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        user.setEnabled(false);
        data.setVisible(false);
        
        akun.setEnabled(true);
        login.setEnabled(true);
        logout.setEnabled(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        new Form_User().setVisible(true);
    }//GEN-LAST:event_userActionPerformed

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed
        // TODO add your handling code here:
        new Pegawai().setVisible(true);
    }//GEN-LAST:event_pegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JMenu akun;
    private javax.swing.JMenu data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField kata;
    private javax.swing.JMenu keluar;
    private javax.swing.JMenuItem login;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem pasien;
    private javax.swing.JMenuItem pegawai;
    private javax.swing.JMenuItem user;
    // End of variables declaration//GEN-END:variables
}
