/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import javax.media.Manager;
import javax.media.Player;
import javax.swing.JFileChooser;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ahmad Fariz
 */
public class MP3 extends javax.swing.JFrame {
    
    DefaultListModel model= new DefaultListModel();
    public Player mp3_ok;

    /**
     * Creates new form MP3
     */
    public MP3() {
        initComponents();
        this.setSize(760,1000);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        daftar = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        buka = new javax.swing.JButton();
        main = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(daftar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 330, 630, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MP2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -140, 760, 1050);

        buka.setText("OPEN");
        buka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukaActionPerformed(evt);
            }
        });
        getContentPane().add(buka);
        buka.setBounds(40, 570, 150, 50);

        main.setText("PLAY");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });
        getContentPane().add(main);
        main.setBounds(220, 570, 150, 50);

        hapus.setText("DELETE");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(400, 570, 150, 50);

        keluar.setText("jButton4");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(580, 570, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukaActionPerformed
        // TODO add your handling code here:
        JFileChooser fc =new JFileChooser();
        JFrame jf = new JFrame();

        FileNameExtensionFilter Filemp3 = new FileNameExtensionFilter(".pm4,.mp3","mp3","wav");
        fc.addChoosableFileFilter(Filemp3);

        int setuju= fc.showOpenDialog(jf.add(fc));
        int posisi= daftar.getModel().getSize();
        if(setuju == JFileChooser.APPROVE_OPTION){
            File file=fc.getSelectedFile();
            String text = file.getPath().toString();
            String[] txt = new String[]{text};
            model.add(posisi, text);
        }
        daftar.setModel(model);
    }//GEN-LAST:event_bukaActionPerformed

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        // TODO add your handling code here:
            if(evt.getActionCommand().equalsIgnoreCase("PLAY")){
            String musik= daftar.getSelectedValue().toString();
            try{
                mp3_ok = Manager.createPlayer(new URL ("File",null,musik));
                mp3_ok.start();
            }
            catch(Exception e){}
            main.setText("STOP");
        }
        if(evt.getActionCommand().equalsIgnoreCase("STOP")){
        mp3_ok.stop();
        main.setText("PLAY");   
        } 
    }//GEN-LAST:event_mainActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int posisi =daftar.getSelectedIndex();
        model.remove(posisi);
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buka;
    private javax.swing.JList<String> daftar;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton main;
    // End of variables declaration//GEN-END:variables
}
